"""baseline schema (T2.3): current 28t/305c frozen at post-audit-hardening

Revision ID: fc4ba7fed054
Revises:
Create Date: 2026-07-07 18:52:08.926459

The Alembic migration spine's baseline (audit T2.3,
docs/t23-alembic-inventory.md). Autogenerated from the ORM models at
tag `post-audit-hardening` (origin/main 2f1eb58) and FROZEN: it is a
byte-exact snapshot of the schema the hand-rolled create_all +
database._ensure_columns produced, NOT an improvement of it (the T2.3
principle). Two independent proofs, both green when this landed:

  * applying this baseline to an empty DB yields the same DB-level
    fingerprint as `Base.metadata.create_all` -
    28 tables / 305 columns, sha256 97537bd4d270b7914e395e57c4caacc8...
    (tools/schema_fingerprint.py), the D24 count;
  * `alembic revision --autogenerate` against a head DB detects NO
    changes (empty upgrade/downgrade) - baseline == models, no drift.

The two constitutional NOT-NULL-with-server-default columns
(knowledge_assets.source_class, source_connectors.lane; both
server_default='PRIMARY', the D30 legacy-PRIMARY-by-construction rule)
are captured verbatim below. Any future schema change is a NEW revision
chained after this one, ratified in docs/DECISIONS.md and mirrored in
test_workbench_projection.py's FROZEN_SCHEMA in the same commit.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc4ba7fed054'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_api_key'), ['api_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_customers_id'), ['id'], unique=False)

    op.create_table('llm_function_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('function', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('function')
    )
    with op.batch_alter_table('llm_function_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_function_configs_id'), ['id'], unique=False)

    op.create_table('principals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('clearance', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('principals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_principals_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_principals_name'), ['name'], unique=True)

    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('principal_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('secret_hash', sa.String(), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('issued_by_credential_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['issued_by_credential_id'], ['credentials.id'], ),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credentials_fingerprint'), ['fingerprint'], unique=True)
        batch_op.create_index(batch_op.f('ix_credentials_id'), ['id'], unique=False)

    op.create_table('identity_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('principal_id', sa.Integer(), nullable=False),
    sa.Column('principal_name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('principal_kind', sa.String(), nullable=False),
    sa.Column('role_snapshot', sa.String(), nullable=True),
    sa.Column('authentication_method', sa.String(), nullable=False),
    sa.Column('credential_fingerprint', sa.String(), nullable=True),
    sa.Column('on_behalf_of_fact_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['on_behalf_of_fact_id'], ['identity_facts.id'], ),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('identity_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_facts_id'), ['id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_id'), ['id'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('identity_fact_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['identity_fact_id'], ['identity_facts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_id'), ['id'], unique=False)

    op.create_table('benchmark_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('expected_claims_json', sa.Text(), nullable=False),
    sa.Column('expected_answer_type', sa.String(), nullable=False),
    sa.Column('required_citation_count', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('min_required_coverage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('benchmark_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_benchmark_questions_id'), ['id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_id'), ['id'], unique=False)

    op.create_table('expert_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('asset_count', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('coverage_score', sa.Float(), nullable=True),
    sa.Column('asset_ids_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expert_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expert_models_id'), ['id'], unique=False)

    op.create_table('external_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('owner_principal_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('granted_scopes_json', sa.Text(), nullable=True),
    sa.Column('coordinates_json', sa.Text(), nullable=True),
    sa.Column('ciphertext', sa.Text(), nullable=False),
    sa.Column('wrapped_data_key', sa.Text(), nullable=False),
    sa.Column('key_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('replaces_credential_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_identity_fact_id', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_identity_fact_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_identity_fact_id'], ['identity_facts.id'], ),
    sa.ForeignKeyConstraint(['owner_principal_id'], ['principals.id'], ),
    sa.ForeignKeyConstraint(['replaces_credential_id'], ['external_credentials.id'], ),
    sa.ForeignKeyConstraint(['revoked_identity_fact_id'], ['identity_facts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('external_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_credentials_fingerprint'), ['fingerprint'], unique=True)
        batch_op.create_index(batch_op.f('ix_external_credentials_id'), ['id'], unique=False)

    op.create_table('agent_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('expert_model_id', sa.Integer(), nullable=True),
    sa.Column('governance_version', sa.String(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('asset_references', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('clearance_level', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('package_hash', sa.String(), nullable=True),
    sa.Column('manifest_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['expert_model_id'], ['expert_models.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_packages_id'), ['id'], unique=False)

    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('table_count', sa.Integer(), nullable=True),
    sa.Column('docling_json', sa.Text(), nullable=True),
    sa.Column('embedding_ref', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_chunks_id'), ['id'], unique=False)

    op.create_table('evaluation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('expert_model_id', sa.Integer(), nullable=True),
    sa.Column('expert_model_version', sa.String(), nullable=True),
    sa.Column('run_type', sa.String(), nullable=True),
    sa.Column('package_version', sa.String(), nullable=True),
    sa.Column('package_hash', sa.String(), nullable=True),
    sa.Column('consumer_model_provider', sa.String(), nullable=True),
    sa.Column('consumer_model_name', sa.String(), nullable=True),
    sa.Column('asset_ids_snapshot', sa.Text(), nullable=False),
    sa.Column('asset_hashes_snapshot', sa.Text(), nullable=False),
    sa.Column('benchmark_question_ids_snapshot', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('average_coverage_score', sa.Float(), nullable=True),
    sa.Column('average_confidence_score', sa.Float(), nullable=True),
    sa.Column('pass_rate', sa.Float(), nullable=True),
    sa.Column('failed_question_ids_json', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['expert_model_id'], ['expert_models.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_runs_id'), ['id'], unique=False)

    op.create_table('source_connectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('root_path', sa.String(), nullable=False),
    sa.Column('include_extensions', sa.String(), nullable=True),
    sa.Column('external_credential_id', sa.Integer(), nullable=True),
    sa.Column('lane', sa.String(), server_default='PRIMARY', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['external_credential_id'], ['external_credentials.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_connectors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_connectors_id'), ['id'], unique=False)

    op.create_table('approval_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('asset_types_json', sa.Text(), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('source_conditions_json', sa.Text(), nullable=True),
    sa.Column('engine_conditions_json', sa.Text(), nullable=True),
    sa.Column('domains_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['source_connectors.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_policies_id'), ['id'], unique=False)

    op.create_table('classification_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rules_json', sa.Text(), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['source_connectors.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classification_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classification_policies_id'), ['id'], unique=False)

    op.create_table('evaluation_question_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_run_id', sa.Integer(), nullable=True),
    sa.Column('benchmark_question_id', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('generated_answer', sa.Text(), nullable=True),
    sa.Column('coverage_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('unsupported_claims_json', sa.Text(), nullable=True),
    sa.Column('citations_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['benchmark_question_id'], ['benchmark_questions.id'], ),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_question_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_question_results_id'), ['id'], unique=False)

    op.create_table('expert_agent_bindings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_package_id', sa.Integer(), nullable=False),
    sa.Column('package_version', sa.String(), nullable=False),
    sa.Column('package_hash', sa.String(), nullable=False),
    sa.Column('selected_provider', sa.String(), nullable=False),
    sa.Column('selected_model_name', sa.String(), nullable=False),
    sa.Column('agent_principal_id', sa.Integer(), nullable=False),
    sa.Column('principal_clearance_at_issue', sa.String(), nullable=False),
    sa.Column('selection_evidence_json', sa.Text(), nullable=False),
    sa.Column('identity_fact_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_package_id'], ['agent_packages.id'], ),
    sa.ForeignKeyConstraint(['agent_principal_id'], ['principals.id'], ),
    sa.ForeignKeyConstraint(['identity_fact_id'], ['identity_facts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expert_agent_bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expert_agent_bindings_id'), ['id'], unique=False)

    op.create_table('ingestion_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('connector_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('files_discovered', sa.Integer(), nullable=True),
    sa.Column('files_ingested', sa.Integer(), nullable=True),
    sa.Column('files_duplicate', sa.Integer(), nullable=True),
    sa.Column('files_changed', sa.Integer(), nullable=True),
    sa.Column('files_failed', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['source_connectors.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingestion_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestion_jobs_id'), ['id'], unique=False)

    op.create_table('knowledge_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('source_citation', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('access_level', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('source_class', sa.String(), server_default='PRIMARY', nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('chunk_id', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_section', sa.String(), nullable=True),
    sa.Column('source_hash', sa.String(), nullable=True),
    sa.Column('extraction_method', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_assets_id'), ['id'], unique=False)

    op.create_table('package_model_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_package_id', sa.Integer(), nullable=False),
    sa.Column('package_version', sa.String(), nullable=False),
    sa.Column('package_hash', sa.String(), nullable=False),
    sa.Column('selected_provider', sa.String(), nullable=False),
    sa.Column('selected_model_name', sa.String(), nullable=False),
    sa.Column('supporting_evaluation_run_ids_json', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('selected_by_principal_id', sa.Integer(), nullable=False),
    sa.Column('selected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_package_id'], ['agent_packages.id'], ),
    sa.ForeignKeyConstraint(['selected_by_principal_id'], ['principals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_package_id')
    )
    with op.batch_alter_table('package_model_selections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_package_model_selections_id'), ['id'], unique=False)

    op.create_table('asset_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('expert_model_id', sa.Integer(), nullable=True),
    sa.Column('source_asset_id', sa.Integer(), nullable=False),
    sa.Column('target_asset_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('verifier_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['expert_model_id'], ['expert_models.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_asset_id'], ['knowledge_assets.id'], ),
    sa.ForeignKeyConstraint(['target_asset_id'], ['knowledge_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_relationships_id'), ['id'], unique=False)

    op.create_table('asset_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('reviewer', sa.String(), nullable=True),
    sa.Column('approver', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('identity_fact_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['knowledge_assets.id'], ),
    sa.ForeignKeyConstraint(['identity_fact_id'], ['identity_facts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_reviews_id'), ['id'], unique=False)

    op.create_table('asset_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_hash', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('identity_fact_id', sa.Integer(), nullable=True),
    sa.Column('supersedes_revision_id', sa.Integer(), nullable=True),
    sa.Column('superseded_by_revision_id', sa.Integer(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['knowledge_assets.id'], ),
    sa.ForeignKeyConstraint(['identity_fact_id'], ['identity_facts.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_revision_id'], ['asset_revisions.id'], ),
    sa.ForeignKeyConstraint(['supersedes_revision_id'], ['asset_revisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_revisions_id'), ['id'], unique=False)

    op.create_table('claim_verdicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('expert_model_id', sa.Integer(), nullable=True),
    sa.Column('evaluation_run_id', sa.Integer(), nullable=True),
    sa.Column('question_result_id', sa.Integer(), nullable=True),
    sa.Column('benchmark_question_id', sa.Integer(), nullable=True),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('supporting_asset_ids_json', sa.Text(), nullable=True),
    sa.Column('contradicting_asset_ids_json', sa.Text(), nullable=True),
    sa.Column('verifier_json', sa.Text(), nullable=True),
    sa.Column('evaluator_type', sa.String(), nullable=True),
    sa.Column('evaluator_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['benchmark_question_id'], ['benchmark_questions.id'], ),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_runs.id'], ),
    sa.ForeignKeyConstraint(['expert_model_id'], ['expert_models.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['question_result_id'], ['evaluation_question_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claim_verdicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_verdicts_id'), ['id'], unique=False)

    op.create_table('quality_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('coverage_score', sa.Integer(), nullable=True),
    sa.Column('freshness_score', sa.Integer(), nullable=True),
    sa.Column('verification_score', sa.Integer(), nullable=True),
    sa.Column('conflict_score', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['knowledge_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quality_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quality_scores_id'), ['id'], unique=False)

    op.create_table('source_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('connector_id', sa.Integer(), nullable=True),
    sa.Column('ingestion_job_id', sa.Integer(), nullable=True),
    sa.Column('source_uri', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('source_modified_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('source_metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['source_connectors.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['ingestion_job_id'], ['ingestion_jobs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_documents_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_documents_id'))

    op.drop_table('source_documents')
    with op.batch_alter_table('quality_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quality_scores_id'))

    op.drop_table('quality_scores')
    with op.batch_alter_table('claim_verdicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_verdicts_id'))

    op.drop_table('claim_verdicts')
    with op.batch_alter_table('asset_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_revisions_id'))

    op.drop_table('asset_revisions')
    with op.batch_alter_table('asset_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_reviews_id'))

    op.drop_table('asset_reviews')
    with op.batch_alter_table('asset_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_relationships_id'))

    op.drop_table('asset_relationships')
    with op.batch_alter_table('package_model_selections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_package_model_selections_id'))

    op.drop_table('package_model_selections')
    with op.batch_alter_table('knowledge_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_assets_id'))

    op.drop_table('knowledge_assets')
    with op.batch_alter_table('ingestion_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestion_jobs_id'))

    op.drop_table('ingestion_jobs')
    with op.batch_alter_table('expert_agent_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expert_agent_bindings_id'))

    op.drop_table('expert_agent_bindings')
    with op.batch_alter_table('evaluation_question_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_question_results_id'))

    op.drop_table('evaluation_question_results')
    with op.batch_alter_table('classification_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classification_policies_id'))

    op.drop_table('classification_policies')
    with op.batch_alter_table('approval_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_policies_id'))

    op.drop_table('approval_policies')
    with op.batch_alter_table('source_connectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_connectors_id'))

    op.drop_table('source_connectors')
    with op.batch_alter_table('evaluation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_runs_id'))

    op.drop_table('evaluation_runs')
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunks_id'))

    op.drop_table('document_chunks')
    with op.batch_alter_table('agent_packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_packages_id'))

    op.drop_table('agent_packages')
    with op.batch_alter_table('external_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_credentials_id'))
        batch_op.drop_index(batch_op.f('ix_external_credentials_fingerprint'))

    op.drop_table('external_credentials')
    with op.batch_alter_table('expert_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expert_models_id'))

    op.drop_table('expert_models')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_id'))

    op.drop_table('documents')
    with op.batch_alter_table('benchmark_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_benchmark_questions_id'))

    op.drop_table('benchmark_questions')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_id'))

    op.drop_table('audit_events')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_id'))

    op.drop_table('projects')
    with op.batch_alter_table('identity_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_facts_id'))

    op.drop_table('identity_facts')
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credentials_id'))
        batch_op.drop_index(batch_op.f('ix_credentials_fingerprint'))

    op.drop_table('credentials')
    with op.batch_alter_table('principals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_principals_name'))
        batch_op.drop_index(batch_op.f('ix_principals_id'))

    op.drop_table('principals')
    with op.batch_alter_table('llm_function_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_function_configs_id'))

    op.drop_table('llm_function_configs')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_id'))
        batch_op.drop_index(batch_op.f('ix_customers_api_key'))

    op.drop_table('customers')
    # ### end Alembic commands ###
